### ISSUE TITLE
Action bar issue

### ISSUE THREAD

**Issue by Micks29** [fasteque/rgb-tool#29]
When I select a value the action bar becomes totally white, see screenshot below:
<a href="http://www.hostingpics.net/viewer.php?id=954148Screenshot20150510185339.png"><img src="http://img15.hostingpics.net/thumbs/mini_954148Screenshot20150510185339.png" alt="Upload images" /></a>
About device: Samsung Galaxy S2 - CM11 (Android Kitkat 4.4.4)

**Comment by fasteque** [comment]
Thank you for reporting this issue - I don't have on my devices which are all Lollipop, so that's the reason why I didn't notice it.

It will be fixed as part of the next release.

**Comment by fasteque** [comment]
It should be fixed now as part of version 1.4.2 which will be released within the end of the next week.

Thanks again for reporting the issue.

**Comment by Micks29** [comment]
Thanks for the quick fix!
Btw I'm working on the French translation for this nice app, stay tuned :)

**Comment by fasteque** [comment]
Great! Let me know when it's ready. Thanks!

**Comment by Micks29** [comment]
Done, pull request created!
