### ISSUE TITLE
Swatches strings in French translation are still in English

### ISSUE THREAD

**Issue by fasteque** [fasteque/rgb-tool#31]
Thanks to @Micks29 the application has now a French translation: to be 100% done, we still need to translate few strings, the ones in the "Swatches" section.

**Comment by Micks29** [comment]
Hi @fasteque, well in fact it's not a bug I've just need more info about "vibrant" and "muted" terms. Can you give me synonyms for these ones?

**Comment by fasteque** [comment]
Hi @Micks29 no worries, I nave just created it so we won't forget about those strings.
The terms are exactly the ones used by Google for the Palette class.

**Comment by fasteque** [comment]
Hi @Micks29 no worries, I have just created it so we won't forget about those strings.
The terms are exactly the ones used by Google for the Palette class.

**Comment by fasteque** [comment]
https://android.googlesource.com/platform/frameworks/support/+/b14fc7c/v7/palette/src/android/support/v7/graphics/Palette.java

**Comment by fasteque** [comment]
http://forum.wordreference.com/threads/muted-color.2523968/

**Comment by Micks29** [comment]
Ok it's more clear with the last link, thanks!
I'm working on it.
