### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by fasteque** [fasteque/rgb-tool#66]
Snow Volf sent me the Russian translation by email, so this is planned for to be released as part of the 1.4.4.

**Comment by fasteque** [comment]
In the provided translation, a bunch of strings are not taken into account:

    <string name="error_open_gallery_image">Error: the image may not be in the local storage</string>

    
    <string name="swatch_vibrant">Vibrant</string>
    <string name="swatch_light_vibrant">Light vibrant</string>
    <string name="swatch_dark_vibrant">Dark vibrant</string>
    <string name="swatch_muted">Muted</string>
    <string name="swatch_light_muted">Light muted</string>
    <string name="swatch_dark_muted">Dark muted</string>

I've contacted Snow Volf to get them (also asking to interact directly here if possible).

**Comment by fasteque** [comment]
<string name="error_open_gallery_image">Ошибка: файл должен находиться на устройстве!</string>


    <string name="swatch_vibrant">Яркий</string>
    <string name="swatch_light_vibrant">Светлый</string>
    <string name="swatch_dark_vibrant">Тёмный</string>
    <string name="swatch_muted">Приглушенный</string>
    <string name="swatch_light_muted">Стветлый приглушенный</string>
    <string name="swatch_dark_muted">Тёмный приглушенный</string>

**Comment by SnowVolf** [comment]
I'll be happy to update the translation in the following versions (if necessary).

**Comment by fasteque** [comment]
Translation integrated, thanks again. I'll let you know for sure in case new strings will require Russian version.
